### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by haiman233** [CTimet/BedrockTechnology#2]
## Description (Required)
后台报错，无法加载

## Server Log / Error Report
[10:19:01 INFO]: [BedrockTechnology] Enabling BedrockTechnology v1.0-beta-220402
[10:19:01 ERROR]: Error occurred while enabling BedrockTechnology v1.0-beta-220402 (Is it up to date?)
[10:19:01 ERROR]: Suspected Plugins: 
[10:19:01 ERROR]:       BedrockTechnology{enabled,ver=1.0-beta-220402,path=plugins/BedrockTechnology_v1.0-beta-220504f0.jar}
[10:19:01 ERROR]: Exception details below: 
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.block.BlockEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:745) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:682) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at io.github.ctimet.bedrocktechnology.initial.BektMain.onEnable(BektMain.java:31) ~[BedrockTechnology_v1.0-beta-220504f0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:336) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1168) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:19:01 INFO]: [BedrockTechnology] Disabling BedrockTechnology v1.0-beta-220402
[10:19:01 WARN]: java.io.FileNotFoundException: plugins/BedrockTechnology/block.dat (No such file or directory)
[10:19:01 WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[10:19:01 WARN]:        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[10:19:01 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[10:19:01 WARN]:        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
[10:19:01 WARN]:        at BedrockTechnology_v1.0-beta-220504f0.jar//io.github.ctimet.bedrocktechnology.event.event.saveData(event.java:172)
[10:19:01 WARN]:        at BedrockTechnology_v1.0-beta-220504f0.jar//io.github.ctimet.bedrocktechnology.initial.BektMain.onDisable(BektMain.java:47)
[10:19:01 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[10:19:01 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405)
[10:19:01 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538)
[10:19:01 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[10:19:01 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[10:19:01 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[10:19:01 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[10:19:01 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669)
[10:19:01 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
[10:19:01 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:336)
[10:19:01 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1168)
[10:19:01 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[10:19:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
## Environment (Required)

 - Minecraft Version:1.18.2
 - CS-CoreLib Version:none
 - Slimefun Version:最新
 - Plugin Version:

**Comment by CTimetbukii** [comment]
此BUG已被修复，请下载最新版本以解决问题
