### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shixinzia** [CTimet/BedrockTechnology#5]
## Environment (Required)

 - Minecraft Version:  1.18.2
 - CS-CoreLib Version: NULL
 - Slimefun Version: V4.9
 - Plugin Version: 38

**Comment by shixinzia** [comment]
[11:26:02] [Server thread/ERROR]: [BedrockTechnology] Item "BEKT_OWNER_REGISTER" from BedrockTechnology vBuild 38 zh-CN(CTimet) (git 23583af) has caused an Error!
[11:26:02] [Server thread/ERROR]: [BedrockTechnology] You can report it here: https://github.com/CTimet/BedrockTechnology/issues

**Comment by shixinzia** [comment]
[11:26:02] [Server thread/ERROR]: [BedrockTechnology] Could not pass "ItemUseHandler" for OwnerRegisterStick - 'BEKT_OWNER_REGISTER' (BedrockTechnology vBuild 38 zh-CN(CTimet) (git 23583af))
java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "this.data" is null
	at me.mrCookieSlime.Slimefun.api.BlockInfoConfig.getKeys(BlockInfoConfig.java:73) ~[Slimefun-6aa9b31-canary.jar:?]
	at me.mrCookieSlime.Slimefun.api.BlockStorage.serializeBlockInfo(BlockStorage.java:496) ~[Slimefun-6aa9b31-canary.jar:?]
	at me.mrCookieSlime.Slimefun.api.BlockStorage.getBlockInfoAsJson(BlockStorage.java:894) ~[Slimefun-6aa9b31-canary.jar:?]
	at io.github.ctimet.bedrocktechnology.data.StickData.putData(StickData.java:53) ~[BedrockTechnology-Build 38 zh-CN(CTimet) (git 23583af).jar:?]
	at io.github.ctimet.bedrocktechnology.core.items.code.fix.OwnerRegisterStick.onClick(OwnerRegisterStick.java:66) ~[BedrockTechnology-Build 38 zh-CN(CTimet) (git 23583af).jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.lambda$rightClickItem$0(SlimefunItemInteractListener.java:100) ~[Slimefun-6aa9b31-canary.jar:?]
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:965) ~[Slimefun-6aa9b31-canary.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.rightClickItem(SlimefunItemInteractListener.java:100) ~[Slimefun-6aa9b31-canary.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:68) ~[Slimefun-6aa9b31-canary.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1073.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:565) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1925) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1531) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: java.io.IOException: Incomplete document
		at com.google.gson.stream.JsonWriter.close(JsonWriter.java:558) ~[gson-2.8.9.jar:?]
		at me.mrCookieSlime.Slimefun.api.BlockStorage.serializeBlockInfo(BlockStorage.java:492) ~[Slimefun-6aa9b31-canary.jar:?]
		at me.mrCookieSlime.Slimefun.api.BlockStorage.getBlockInfoAsJson(BlockStorage.java:894) ~[Slimefun-6aa9b31-canary.jar:?]
		at io.github.ctimet.bedrocktechnology.data.StickData.putData(StickData.java:53) ~[BedrockTechnology-Build 38 zh-CN(CTimet) (git 23583af).jar:?]
		at io.github.ctimet.bedrocktechnology.core.items.code.fix.OwnerRegisterStick.onClick(OwnerRegisterStick.java:66) ~[BedrockTechnology-Build 38 zh-CN(CTimet) (git 23583af).jar:?]
		at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.lambda$rightClickItem$0(SlimefunItemInteractListener.java:100) ~[Slimefun-6aa9b31-canary.jar:?]
		at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:965) ~[Slimefun-6aa9b31-canary.jar:?]
		at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.rightClickItem(SlimefunItemInteractListener.java:100) ~[Slimefun-6aa9b31-canary.jar:?]
		at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:68) ~[Slimefun-6aa9b31-canary.jar:?]
		at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1073.execute(Unknown Source) ~[?:?]
		at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
		at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
		at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
		at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
		at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:565) ~[?:?]
		at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1925) ~[?:?]
		at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
		at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
		at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
		at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
		at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
		at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
		at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
		at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1531) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by CTimetbukii** [comment]
关闭，无法修复。该异常在BlockStorage.getBlockInfoAsJson(block.getLocation())中抛出，而在调用此方法前，插件已经进行了BlockStorage.check(block) != null的判空操作，确认是Slimefun方块才进行的注册行为。由于异常在Slimefun的代码中抛出且在此之前我们已经将能做的都做了（对方块进行判断是否是sf方块，以及判断方块是否禁止注册，判断注册信息是否读取完全）。所以对于此异常我们实在是无能为力。要不然你试试向Slimefun的issues提交这个bug(对于Slimefun方块在getBlockInfoAsJson时抛出NullPointerException)？
