### ISSUE TITLE
重复注册的提示问题（已启用mysql）

### ISSUE THREAD

**Issue by JiangQiYan713** [CTimet/BedrockTechnology#7]
## Description (Required)
数据存储本身没有问题
暂时不能确定插件能否正常修复==
1.
在第一次注册sf方块时，（使用注册棒）成功在数据库添加了对应的方块数据
在使用范围注册棒时聊天栏没有提示，但是后台出现了大量重复报错
重复注册时仍旧显示方块已成功注册而不是提示不可重复注册
后台出现报错
2.
在使用范围注册棒时聊天栏没有提示，但是后台出现了大量重复报错

## Expected behavior (Required)
后台不会输出报错，并且聊天栏显示不可重复注册

## Server Log / Error Report
1.第一次注册后
无
2.重复注册后
```
[19:26:25 WARN]: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '4288.0&64.0&4220.0&world' for key 'PRIMARY'
[19:26:25 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
[19:26:25 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:26:25 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[19:26:25 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
[19:26:25 WARN]:        at BedrockTechnology-Build 41 zh-CN(CTimet) (git 5dccd8e).jar//com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
[19:26:25 WARN]:        at BedrockTechnology-Build 41 zh-CN(CTimet) (git 5dccd8e).jar//io.github.ctimet.bedrocktechnology.data.MysqlHandler.lambda$putData$0(MysqlHandler.java:85)
[19:26:25 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:26:25 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:26:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:26:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:26:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
>
```

## Environment (Required)

 - Minecraft Version:paper 404（Minecraft1.19.3）
 - CS-CoreLib Version:没有安装
 - Slimefun Version:2023.02release
 - Plugin Version: 41

**Comment by xiaoyiluck666** [comment]
我也遇到了相同的问题
